/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package montecarlo.view;

import java.awt.Color;
import java.awt.FileDialog;
import java.awt.Frame;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import montecarlo.data.Field;
import montecarlo.model.MonteCarloModel;
import montecarlo.model.MonteCarloTransitionRule;
import montecarlo.model.abstr.INeighborhood;
import montecarlo.model.abstr.ITransitionRule;
import montecarlo.model.impl.Moore;
import montecarlo.service.WorkerThread;
import montecarlo.view.listeners.OnClickField;

/**
 *
 * @author student
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        jLabel3.setText(jSlider1.getValue()+"");
        
        fieldJPanel1.setListener(new OnClickField() {
            @Override
            public void onClick(int x, int y) { 
               INeighborhood iNeighborhood = new Moore();
                ITransitionRule rule = new MonteCarloTransitionRule(); 
                Field input = fieldJPanel1.getData()[x][y];
                Field[][] boundary = iNeighborhood.getBoundary(fieldJPanel1.getData(), x, y, isPeriodic() );
                Field output = rule.transition(boundary , 10 , input);
               
                fieldJPanel1.getData()[x][y] = output;
                fieldJPanel1.repaint();
            }

            @Override
            public void onMove(int x, int y) { 
                Field input = fieldJPanel1.getData()[x][y];
                jLabel5.setText(input.getColor().toString());
            }
            
            
            
        });
        
    }
    
    private boolean isPeriodic(){
        return jCheckBox1.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldJPanel1 = new montecarlo.view.FieldJPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSlider1 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout fieldJPanel1Layout = new javax.swing.GroupLayout(fieldJPanel1);
        fieldJPanel1.setLayout(fieldJPanel1Layout);
        fieldJPanel1Layout.setHorizontalGroup(
            fieldJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        fieldJPanel1Layout.setVerticalGroup(
            fieldJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jLabel1.setText("Monte Carlo");

        jLabel2.setText("Size -");

        jCheckBox1.setText("Periodic condition");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jSlider1.setMaximum(300);
        jSlider1.setMinimum(100);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel4.setText("Count iterations:");

        jTextField1.setText("100");

        jButton2.setText("Next step");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Randomize");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setText("Monte Carlo SRX Heterogenous");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Monte Carlo SRX Homogenous");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Show energy");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("New nucleons anywhere");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton12))
        );

        jLabel5.setText(" ");

        jButton8.setText("Select grain");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton7.setText("Dual phase (MC -> CA)");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("Dual phase (CA -> MC)");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setText("Stop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Resume");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton13.setText("New nucleons on Bondary");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton1))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        jLabel3.setText(jSlider1.getValue()+"");
    }//GEN-LAST:event_jSlider1StateChanged

    WorkerThread anim;
    
    MonteCarloModel model;
    
    //start
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(anim!=null){
            anim.stopAnim();
        }
        model = new MonteCarloModel( 
                fieldJPanel1 , 
                jSlider1.getValue(),
                new Moore(),
                Integer.parseInt(jTextField1.getText()),
                isPeriodic()
        );  
        anim = new WorkerThread(model, endAction);
        anim.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    // następny krok
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(model==null){
            model = new MonteCarloModel( 
                fieldJPanel1 , 
                jSlider1.getValue(),
                new Moore(),
                Integer.parseInt(jTextField1.getText()),
                isPeriodic()
            ); 
        }
        model.step(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    // stop
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(anim!=null){
            anim.stopAnim();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    //wznowienie
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       if(anim!=null){
            anim.stopAnim();
        }
        if(model!=null){
           anim = new WorkerThread(model, endAction);
            anim.start(); 
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    //wypełnienie panelu
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(model==null){
            model = new MonteCarloModel( 
                fieldJPanel1 , 
                jSlider1.getValue(),
                new Moore(),
                Integer.parseInt(jTextField1.getText()),
                isPeriodic()
            ); 
        }
        model.randomize();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        FileDialog dialog = new FileDialog((Frame)null, "Select File to Open");
        dialog.setMode(FileDialog.LOAD);
        dialog.setVisible(true);
        String fileName = dialog.getFile();
        System.out.println(fileName + " chosen.");
        
        Field [][] oldPanel = fieldJPanel1.getData();
        Field[][] dateFromTXT =null;
    
    BufferedReader br = null;
        try {
            br = new BufferedReader(new FileReader(fileName));
        } 
        
        catch (FileNotFoundException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
        StringBuilder sb = new StringBuilder();
        String line;

        while ((line = br.readLine()) != null) {
            
        String[] parts = line.split(" ", 5);
        if (parts.length >= 5)
        {
            int xx = Integer.parseInt(parts[0]);
            int yy = Integer.parseInt(parts[1]);
            int phase = Integer.parseInt(parts[2]);
            int type = Integer.parseInt(parts[3]);
            int color = Integer.parseInt(parts[4]);
            
            if(color != -1)
            {
            Color color_1 = new Color(color);
            
            oldPanel[xx][yy].setColor(color_1);
            //oldPanel[xx][yy].setP(phase);
            //oldPanel[xx][yy].setType(type);
            }
            
        }
        else 
        {
            String[] parts_1 = line.split(" ", 3);
            
            int x_height = Integer.parseInt(parts_1[1]);
            int y_width = Integer.parseInt(parts_1[2]);
            
            System.out.println("ignoring line: " + line);
            dateFromTXT = new Field[x_height][y_width];
        }
        }
        
        fieldJPanel1.invalidate();
        fieldJPanel1.validate();
        fieldJPanel1.repaint(); 
    }   
        
    catch (IOException ex) {
        Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
    } 
    finally {
           try {
               br.close();
           } 
           catch (IOException ex) {
               Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Field[][] dateToTXT = fieldJPanel1.getData();
        PrintWriter writer = null;
        if(dateToTXT == null){
           return;
        }
        try {
            writer = new PrintWriter("../NucleonsGrowth/Export_MC_CA.txt", "UTF-8");
            writer.format(" %d %d\r\n",dateToTXT.length,dateToTXT.length);
            for(int x=0 ;x<dateToTXT.length ;x++){
                for(int y=0; y<dateToTXT[x].length;y++){
                    String col_1 = String.format("#%06x", dateToTXT[x][y].getColor().getRGB() & 0x00FFFFFF);
                    int colRGB = dateToTXT[x][y].getColor().getRGB();
                    //System.out.format("%d %d %f %d \n", x ,y, dateToTXT[x][y].getP(), dateToTXT[x][y].getType(), dateToTXT[x][y].getColor()); 
                    writer.format("%d %d %d %d %d\r\n", x ,y, (int)dateToTXT[x][y].getP(),
                            dateToTXT[x][y].getType(), colRGB);
                }
            }
        }
        catch(FileNotFoundException ex){
            System.out.println("error write to file :( ");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            if(writer != null)
            writer.close();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    //select grain
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Field[][] fields = fieldJPanel1.getData();
         
         Random generator = new Random();
         
         int wybr_i = generator.nextInt(fields.length);
         int wybr_j = generator.nextInt(fields.length);
         
         Color color_selected = fields[wybr_i][wybr_j].getColor();
         String color_const_selected = String.format("#%06x", color_selected.getRGB() & 0x00FFFFFF);
         
         
         for(int x=0 ;x<fields.length-1 ;x++)
        {
            for(int y=0; y<fields[x].length-1;y++)
            {
                Color color_1_x = fields[x][y].getColor();
                Color color_2_x = fields[x+1][y].getColor();
                Color color_1_y = fields[x][y].getColor();
                Color color_2_y = fields[x][y+1].getColor();
                
                
                String col_1_x = String.format("#%06x", color_1_x.getRGB() & 0x00FFFFFF);
                String col_2_x = String.format("#%06x", color_2_x.getRGB() & 0x00FFFFFF);
                
                String col_1_y = String.format("#%06x", color_1_y.getRGB() & 0x00FFFFFF);
                String col_2_y = String.format("#%06x", color_2_y.getRGB() & 0x00FFFFFF);
                
                if ((!(col_1_x.equals(color_const_selected))) || 
                    (!(col_2_x.equals(color_const_selected))) )
                { 
                    fields[x][y].setColor(Color.WHITE);
                    if(((x+1)== fields.length-1)){
                        fields[x+1][y].setColor(Color.WHITE);
                    }
                    if(((y+1)== fields.length-1)){
                        fields[x][y+1].setColor(Color.WHITE);
                    }
                    if(((x+1)== fields.length-1)&&((y+1)== fields.length-1))
                    {
                        fields[x+1][y+1].setColor(Color.WHITE);
                    }
                }
            }
        }
         
        fieldJPanel1.invalidate();
        fieldJPanel1.validate();
        fieldJPanel1.repaint();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         Field[][] fields = fieldJPanel1.getData();
        int[][] allNucleonsToInclusions = new int[fields.length*50][2];
        int iteratorForInclusions = 0;
        
        for(int x=0 ;x<fields.length-1 ;x++)
        {
            for(int y=0; y<fields[x].length-1;y++)
            {
                Color color_1_x = fields[x][y].getColor();
                Color color_2_x = fields[x+1][y].getColor();
                Color color_1_y = fields[x][y].getColor();
                Color color_2_y = fields[x][y+1].getColor();
                
                String col_1_x = String.format("#%06x", color_1_x.getRGB() & 0x00FFFFFF);
                String col_2_x = String.format("#%06x", color_2_x.getRGB() & 0x00FFFFFF);
                
                String col_1_y = String.format("#%06x", color_1_y.getRGB() & 0x00FFFFFF);
                String col_2_y = String.format("#%06x", color_2_y.getRGB() & 0x00FFFFFF);
                              
                if ((!(col_1_x.equals(col_2_x))) || (!(col_1_y.equals(col_2_y))))
                { 
                    allNucleonsToInclusions[iteratorForInclusions][0] = x;
                    allNucleonsToInclusions[iteratorForInclusions][1] = y;
                    
                    fields[x][y].setColor(Color.GREEN);
                    fields[x][y].H=5;
                    if(((x+1)== fields.length-1)){
                        fields[x+1][y].setColor(Color.GREEN);
                        fields[x+1][y].H=5;
                    }
                    if(((y+1)== fields.length-1)){
                        fields[x][y+1].setColor(Color.GREEN);
                        fields[x][y+1].H=5;
                    }
                    if(((x+1)== fields.length-1)&&((y+1)== fields.length-1))
                    {
                        fields[x+1][y+1].setColor(Color.GREEN);
                        fields[x+1][y+1].H=5;
                    }
                    
                    iteratorForInclusions++;                   
                }
                else
                {
                    
                    fields[x][y].setColor(Color.BLUE);
                    fields[x][y].H=2;
                    if(((x+1)== fields.length-1)){
                        fields[x+1][y].setColor(Color.BLUE);
                        fields[x+1][y].H=2;
                    }
                    if(((y+1)== fields.length-1)){
                        fields[x][y+1].setColor(Color.BLUE);
                        fields[x][y+1].H=2;
                    }
                    if(((x+1)== fields.length-1)&&((y+1)== fields.length-1))
                    {
                        fields[x+1][y+1].setColor(Color.BLUE);
                        fields[x+1][y+1].H=2;
                    }
                }
            }
        }
        
        System.out.println("Number of boundary grains: " + iteratorForInclusions);
        double size = (double)fields.length;
        System.out.println("Number of all grains: " + size*size);

        double percent = (iteratorForInclusions/(size*size))*100;

        System.out.println("% GB: " + percent);
        
        fieldJPanel1.invalidate();
        fieldJPanel1.validate();
        fieldJPanel1.repaint(); 
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Field[][] fields = fieldJPanel1.getData();
        int[][] allNucleonsToInclusions = new int[fields.length*50][2];
        int iteratorForInclusions = 0;
        
        for(int x=0 ;x<fields.length ;x++)
        {
            for(int y=0; y<fields[x].length;y++)
            {
                fields[x][y].setColor(Color.BLUE);
                fields[x][y].H=2;
            }
        }
        
        fieldJPanel1.invalidate();
        fieldJPanel1.validate();
        fieldJPanel1.repaint(); 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Field[][] dateToTXT = fieldJPanel1.getData();
        PrintWriter writer = null;
        if(dateToTXT == null){
           return;
        }
        try {
            writer = new PrintWriter("CellWithEnergy.txt", "UTF-8");
            writer.format(" %d %d\r\n",dateToTXT.length,dateToTXT.length);
            for(int x=0 ;x<dateToTXT.length ;x++){
                for(int y=0; y<dateToTXT[x].length;y++){
                    writer.format("%d %d %d\r\n", x ,y, dateToTXT[x][y].getH());
                }
            }
        }
        catch(FileNotFoundException ex){
            System.out.println("error write to file :( ");
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            if(writer != null)
            writer.close();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Field[][] fields = fieldJPanel1.getData();
        
        Random generator = new Random();
        
        int numberOfNewNucleons = 100;
        
        for (int i=0; i<numberOfNewNucleons; i++)
        {
            int x_rand = generator.nextInt(fields.length);
            int y_rand = generator.nextInt(fields.length);
            
            int colorR = generator.nextInt(250);
            int colorG = generator.nextInt(250);
            int colorB = generator.nextInt(250);
            
            
            fields[x_rand][y_rand].setColor(new Color(colorR, colorG, colorB));
            //fields[x_rand][y_rand].
        }
        fieldJPanel1.invalidate();
        fieldJPanel1.validate();
        fieldJPanel1.repaint();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        
        int countOfIncludions = 50; // ilosc wtracen
        int sizeOfInclusions = 1;
        
        boolean circleInclusions = false; // false -kwadraty, true- kółka
        
        int iteratorForInclusions = 0;
        Field[][] fields = fieldJPanel1.getData();
        int[][] allNucleonsToInclusions = new int[fields.length*50][2];
        
        for(int x=0 ;x<fields.length-1 ;x++)
        {
            for(int y=0; y<fields[x].length;y++)
            {
                Color color_1 = fields[x][y].getColor();
                Color color_2 = fields[x+1][y].getColor();
                
                String col_1 = String.format("#%06x", color_1.getRGB() & 0x00FFFFFF);
                String col_2 = String.format("#%06x", color_2.getRGB() & 0x00FFFFFF);
                              
                if (!(col_1.equals(col_2)))
                { 
                    allNucleonsToInclusions[iteratorForInclusions][0] = x;
                    allNucleonsToInclusions[iteratorForInclusions][1] = y;
                    
                    iteratorForInclusions++;                   
                }
            }
        }
        Random rand = new Random();
        
        
        int i = 0;
        while(i<countOfIncludions){
            
            int n = rand.nextInt(iteratorForInclusions)+1;
        
            for(int x=0 ;x<fields.length-1 ;x++)
            {
                for(int y=0; y<fields[x].length;y++)
                {
                    if(!circleInclusions)
                    {
                        for (int xi = 0; xi < sizeOfInclusions; xi++)
                        {
                            for (int xj=0; xj<sizeOfInclusions; xj++)
                            {
                                if(allNucleonsToInclusions[n][0]+xi== x && allNucleonsToInclusions[n][1]+xj == y)
                                {
                                    int colorR = rand.nextInt(250);
                                    int colorG = rand.nextInt(250);
                                    int colorB = rand.nextInt(250);
                                    fields[x][y].setColor(new Color(colorR, colorG, colorB));
                                }
                            }
                        }
                    }
                    else
                    {
                        //okragle wtracenia
                        int x2 = allNucleonsToInclusions[n][0];
                        int y2 = allNucleonsToInclusions[n][1];
                        int r = sizeOfInclusions;


                        int dx = x2 - x; // horizontal offset
                        int dy = y2 - y; // vertical offset
                        if ( (dx*dx + dy*dy) <= (r*r) )
                        {
                            int colorR = rand.nextInt(250);
                            int colorG = rand.nextInt(250);
                            int colorB = rand.nextInt(250);
                            fields[x][y].setColor(new Color(colorR, colorG, colorB));
                        }
                    }
                }
            }
            i++;
        }
        fieldJPanel1.invalidate();
        fieldJPanel1.validate();
        fieldJPanel1.repaint(); 
    }//GEN-LAST:event_jButton13ActionPerformed

    private Runnable endAction = new Runnable() {
        @Override
        public void run() { 
            
        }
    };
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private montecarlo.view.FieldJPanel fieldJPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
